declare module 'dashboard/Dashboard'
declare module 'meus_eventos/MyEvents'
declare module 'meus_eventos/CreateEvent'
declare module 'meus_eventos/EditEvent'
declare module 'meus_eventos/EventDetails'
declare module 'inscricao_evento/EventSubscribe'
declare module 'inscricao_evento/SubscribeConfirmation'